# Generated by Django 3.1 on 2020-08-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200815_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlink',
            old_name='answer',
            new_name='answers',
        ),
    ]
